//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacLearningObservation) DeepCopyInto(out *MacLearningObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(float64)
		**out = **in
	}
	if in.LimitPolicy != nil {
		in, out := &in.LimitPolicy, &out.LimitPolicy
		*out = new(string)
		**out = **in
	}
	if in.UnicastFloodingAllowed != nil {
		in, out := &in.UnicastFloodingAllowed, &out.UnicastFloodingAllowed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacLearningObservation.
func (in *MacLearningObservation) DeepCopy() *MacLearningObservation {
	if in == nil {
		return nil
	}
	out := new(MacLearningObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacLearningParameters) DeepCopyInto(out *MacLearningParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(float64)
		**out = **in
	}
	if in.LimitPolicy != nil {
		in, out := &in.LimitPolicy, &out.LimitPolicy
		*out = new(string)
		**out = **in
	}
	if in.UnicastFloodingAllowed != nil {
		in, out := &in.UnicastFloodingAllowed, &out.UnicastFloodingAllowed
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacLearningParameters.
func (in *MacLearningParameters) DeepCopy() *MacLearningParameters {
	if in == nil {
		return nil
	}
	out := new(MacLearningParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacManagementSwitchingProfile) DeepCopyInto(out *MacManagementSwitchingProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacManagementSwitchingProfile.
func (in *MacManagementSwitchingProfile) DeepCopy() *MacManagementSwitchingProfile {
	if in == nil {
		return nil
	}
	out := new(MacManagementSwitchingProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MacManagementSwitchingProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacManagementSwitchingProfileList) DeepCopyInto(out *MacManagementSwitchingProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MacManagementSwitchingProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacManagementSwitchingProfileList.
func (in *MacManagementSwitchingProfileList) DeepCopy() *MacManagementSwitchingProfileList {
	if in == nil {
		return nil
	}
	out := new(MacManagementSwitchingProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MacManagementSwitchingProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacManagementSwitchingProfileObservation) DeepCopyInto(out *MacManagementSwitchingProfileObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MacChangeAllowed != nil {
		in, out := &in.MacChangeAllowed, &out.MacChangeAllowed
		*out = new(bool)
		**out = **in
	}
	if in.MacLearning != nil {
		in, out := &in.MacLearning, &out.MacLearning
		*out = make([]MacLearningObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacManagementSwitchingProfileObservation.
func (in *MacManagementSwitchingProfileObservation) DeepCopy() *MacManagementSwitchingProfileObservation {
	if in == nil {
		return nil
	}
	out := new(MacManagementSwitchingProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacManagementSwitchingProfileParameters) DeepCopyInto(out *MacManagementSwitchingProfileParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.MacChangeAllowed != nil {
		in, out := &in.MacChangeAllowed, &out.MacChangeAllowed
		*out = new(bool)
		**out = **in
	}
	if in.MacLearning != nil {
		in, out := &in.MacLearning, &out.MacLearning
		*out = make([]MacLearningParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacManagementSwitchingProfileParameters.
func (in *MacManagementSwitchingProfileParameters) DeepCopy() *MacManagementSwitchingProfileParameters {
	if in == nil {
		return nil
	}
	out := new(MacManagementSwitchingProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacManagementSwitchingProfileSpec) DeepCopyInto(out *MacManagementSwitchingProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacManagementSwitchingProfileSpec.
func (in *MacManagementSwitchingProfileSpec) DeepCopy() *MacManagementSwitchingProfileSpec {
	if in == nil {
		return nil
	}
	out := new(MacManagementSwitchingProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacManagementSwitchingProfileStatus) DeepCopyInto(out *MacManagementSwitchingProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacManagementSwitchingProfileStatus.
func (in *MacManagementSwitchingProfileStatus) DeepCopy() *MacManagementSwitchingProfileStatus {
	if in == nil {
		return nil
	}
	out := new(MacManagementSwitchingProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagObservation) DeepCopyInto(out *TagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagObservation.
func (in *TagObservation) DeepCopy() *TagObservation {
	if in == nil {
		return nil
	}
	out := new(TagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagParameters) DeepCopyInto(out *TagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagParameters.
func (in *TagParameters) DeepCopy() *TagParameters {
	if in == nil {
		return nil
	}
	out := new(TagParameters)
	in.DeepCopyInto(out)
	return out
}
