/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyIpsecVpnDpdProfileObservation struct {

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	DpdProbeInterval *float64 `json:"dpdProbeInterval,omitempty" tf:"dpd_probe_interval,omitempty"`

	DpdProbeMode *string `json:"dpdProbeMode,omitempty" tf:"dpd_probe_mode,omitempty"`

	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// NSX ID for this resource
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Policy path for this resource
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	RetryCount *float64 `json:"retryCount,omitempty" tf:"retry_count,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []TagObservation `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyIpsecVpnDpdProfileParameters struct {

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// +kubebuilder:validation:Optional
	DpdProbeInterval *float64 `json:"dpdProbeInterval,omitempty" tf:"dpd_probe_interval,omitempty"`

	// +kubebuilder:validation:Optional
	DpdProbeMode *string `json:"dpdProbeMode,omitempty" tf:"dpd_probe_mode,omitempty"`

	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// NSX ID for this resource
	// +kubebuilder:validation:Optional
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// +kubebuilder:validation:Optional
	RetryCount *float64 `json:"retryCount,omitempty" tf:"retry_count,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []TagParameters `json:"tag,omitempty" tf:"tag,omitempty"`
}

type TagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type TagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// PolicyIpsecVpnDpdProfileSpec defines the desired state of PolicyIpsecVpnDpdProfile
type PolicyIpsecVpnDpdProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyIpsecVpnDpdProfileParameters `json:"forProvider"`
}

// PolicyIpsecVpnDpdProfileStatus defines the observed state of PolicyIpsecVpnDpdProfile.
type PolicyIpsecVpnDpdProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyIpsecVpnDpdProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyIpsecVpnDpdProfile is the Schema for the PolicyIpsecVpnDpdProfiles API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type PolicyIpsecVpnDpdProfile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	Spec   PolicyIpsecVpnDpdProfileSpec   `json:"spec"`
	Status PolicyIpsecVpnDpdProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyIpsecVpnDpdProfileList contains a list of PolicyIpsecVpnDpdProfiles
type PolicyIpsecVpnDpdProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyIpsecVpnDpdProfile `json:"items"`
}

// Repository type metadata.
var (
	PolicyIpsecVpnDpdProfile_Kind             = "PolicyIpsecVpnDpdProfile"
	PolicyIpsecVpnDpdProfile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyIpsecVpnDpdProfile_Kind}.String()
	PolicyIpsecVpnDpdProfile_KindAPIVersion   = PolicyIpsecVpnDpdProfile_Kind + "." + CRDGroupVersion.String()
	PolicyIpsecVpnDpdProfile_GroupVersionKind = CRDGroupVersion.WithKind(PolicyIpsecVpnDpdProfile_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyIpsecVpnDpdProfile{}, &PolicyIpsecVpnDpdProfileList{})
}
