/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ContextObservation struct {

	// Id of the project which the resource belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type ContextParameters struct {

	// Id of the project which the resource belongs to.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`
}

type PolicyDhcpRelayObservation struct {

	// Resource context
	Context []ContextObservation `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// NSX ID for this resource
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Policy path for this resource
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	ServerAddresses []*string `json:"serverAddresses,omitempty" tf:"server_addresses,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []TagObservation `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyDhcpRelayParameters struct {

	// Resource context
	// +kubebuilder:validation:Optional
	Context []ContextParameters `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// NSX ID for this resource
	// +kubebuilder:validation:Optional
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// +kubebuilder:validation:Optional
	ServerAddresses []*string `json:"serverAddresses,omitempty" tf:"server_addresses,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []TagParameters `json:"tag,omitempty" tf:"tag,omitempty"`
}

type TagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type TagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// PolicyDhcpRelaySpec defines the desired state of PolicyDhcpRelay
type PolicyDhcpRelaySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyDhcpRelayParameters `json:"forProvider"`
}

// PolicyDhcpRelayStatus defines the observed state of PolicyDhcpRelay.
type PolicyDhcpRelayStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyDhcpRelayObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyDhcpRelay is the Schema for the PolicyDhcpRelays API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type PolicyDhcpRelay struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.serverAddresses)",message="serverAddresses is a required parameter"
	Spec   PolicyDhcpRelaySpec   `json:"spec"`
	Status PolicyDhcpRelayStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyDhcpRelayList contains a list of PolicyDhcpRelays
type PolicyDhcpRelayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyDhcpRelay `json:"items"`
}

// Repository type metadata.
var (
	PolicyDhcpRelay_Kind             = "PolicyDhcpRelay"
	PolicyDhcpRelay_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyDhcpRelay_Kind}.String()
	PolicyDhcpRelay_KindAPIVersion   = PolicyDhcpRelay_Kind + "." + CRDGroupVersion.String()
	PolicyDhcpRelay_GroupVersionKind = CRDGroupVersion.WithKind(PolicyDhcpRelay_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyDhcpRelay{}, &PolicyDhcpRelayList{})
}
