/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyDhcpServerContextObservation struct {

	// Id of the project which the resource belongs to.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`
}

type PolicyDhcpServerContextParameters struct {

	// Id of the project which the resource belongs to.
	// +kubebuilder:validation:Required
	ProjectID *string `json:"projectId" tf:"project_id,omitempty"`
}

type PolicyDhcpServerObservation struct {

	// Resource context
	Context []PolicyDhcpServerContextObservation `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Edge Cluster path
	EdgeClusterPath *string `json:"edgeClusterPath,omitempty" tf:"edge_cluster_path,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP Address lease time in seconds
	LeaseTime *float64 `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// NSX ID for this resource
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// Policy path for this resource
	Path *string `json:"path,omitempty" tf:"path,omitempty"`

	// The first edge node is assigned as active edge, and second one as standby edge
	PreferredEdgePaths []*string `json:"preferredEdgePaths,omitempty" tf:"preferred_edge_paths,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// DHCP server address in CIDR format
	ServerAddresses []*string `json:"serverAddresses,omitempty" tf:"server_addresses,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []PolicyDhcpServerTagObservation `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyDhcpServerParameters struct {

	// Resource context
	// +kubebuilder:validation:Optional
	Context []PolicyDhcpServerContextParameters `json:"context,omitempty" tf:"context,omitempty"`

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Edge Cluster path
	// +kubebuilder:validation:Optional
	EdgeClusterPath *string `json:"edgeClusterPath,omitempty" tf:"edge_cluster_path,omitempty"`

	// IP Address lease time in seconds
	// +kubebuilder:validation:Optional
	LeaseTime *float64 `json:"leaseTime,omitempty" tf:"lease_time,omitempty"`

	// NSX ID for this resource
	// +kubebuilder:validation:Optional
	NsxID *string `json:"nsxId,omitempty" tf:"nsx_id,omitempty"`

	// The first edge node is assigned as active edge, and second one as standby edge
	// +kubebuilder:validation:Optional
	PreferredEdgePaths []*string `json:"preferredEdgePaths,omitempty" tf:"preferred_edge_paths,omitempty"`

	// DHCP server address in CIDR format
	// +kubebuilder:validation:Optional
	ServerAddresses []*string `json:"serverAddresses,omitempty" tf:"server_addresses,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []PolicyDhcpServerTagParameters `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyDhcpServerTagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type PolicyDhcpServerTagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// PolicyDhcpServerSpec defines the desired state of PolicyDhcpServer
type PolicyDhcpServerSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyDhcpServerParameters `json:"forProvider"`
}

// PolicyDhcpServerStatus defines the observed state of PolicyDhcpServer.
type PolicyDhcpServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyDhcpServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyDhcpServer is the Schema for the PolicyDhcpServers API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type PolicyDhcpServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	Spec   PolicyDhcpServerSpec   `json:"spec"`
	Status PolicyDhcpServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyDhcpServerList contains a list of PolicyDhcpServers
type PolicyDhcpServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyDhcpServer `json:"items"`
}

// Repository type metadata.
var (
	PolicyDhcpServer_Kind             = "PolicyDhcpServer"
	PolicyDhcpServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyDhcpServer_Kind}.String()
	PolicyDhcpServer_KindAPIVersion   = PolicyDhcpServer_Kind + "." + CRDGroupVersion.String()
	PolicyDhcpServer_GroupVersionKind = CRDGroupVersion.WithKind(PolicyDhcpServer_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyDhcpServer{}, &PolicyDhcpServerList{})
}
