//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeManager) DeepCopyInto(out *ComputeManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeManager.
func (in *ComputeManager) DeepCopy() *ComputeManager {
	if in == nil {
		return nil
	}
	out := new(ComputeManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeManagerList) DeepCopyInto(out *ComputeManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComputeManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeManagerList.
func (in *ComputeManagerList) DeepCopy() *ComputeManagerList {
	if in == nil {
		return nil
	}
	out := new(ComputeManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ComputeManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeManagerObservation) DeepCopyInto(out *ComputeManagerObservation) {
	*out = *in
	if in.AccessLevelForOidc != nil {
		in, out := &in.AccessLevelForOidc, &out.AccessLevelForOidc
		*out = new(string)
		**out = **in
	}
	if in.CreateServiceAccount != nil {
		in, out := &in.CreateServiceAccount, &out.CreateServiceAccount
		*out = new(bool)
		**out = **in
	}
	if in.Credential != nil {
		in, out := &in.Credential, &out.Credential
		*out = make([]CredentialObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ExtensionCertificate != nil {
		in, out := &in.ExtensionCertificate, &out.ExtensionCertificate
		*out = make([]ExtensionCertificateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MultiNsx != nil {
		in, out := &in.MultiNsx, &out.MultiNsx
		*out = new(bool)
		**out = **in
	}
	if in.OriginType != nil {
		in, out := &in.OriginType, &out.OriginType
		*out = new(string)
		**out = **in
	}
	if in.ReverseProxyHTTPSPort != nil {
		in, out := &in.ReverseProxyHTTPSPort, &out.ReverseProxyHTTPSPort
		*out = new(float64)
		**out = **in
	}
	if in.Revision != nil {
		in, out := &in.Revision, &out.Revision
		*out = new(float64)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
	if in.SetAsOidcProvider != nil {
		in, out := &in.SetAsOidcProvider, &out.SetAsOidcProvider
		*out = new(bool)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeManagerObservation.
func (in *ComputeManagerObservation) DeepCopy() *ComputeManagerObservation {
	if in == nil {
		return nil
	}
	out := new(ComputeManagerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeManagerParameters) DeepCopyInto(out *ComputeManagerParameters) {
	*out = *in
	if in.AccessLevelForOidc != nil {
		in, out := &in.AccessLevelForOidc, &out.AccessLevelForOidc
		*out = new(string)
		**out = **in
	}
	if in.CreateServiceAccount != nil {
		in, out := &in.CreateServiceAccount, &out.CreateServiceAccount
		*out = new(bool)
		**out = **in
	}
	if in.Credential != nil {
		in, out := &in.Credential, &out.Credential
		*out = make([]CredentialParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.ExtensionCertificate != nil {
		in, out := &in.ExtensionCertificate, &out.ExtensionCertificate
		*out = make([]ExtensionCertificateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MultiNsx != nil {
		in, out := &in.MultiNsx, &out.MultiNsx
		*out = new(bool)
		**out = **in
	}
	if in.OriginType != nil {
		in, out := &in.OriginType, &out.OriginType
		*out = new(string)
		**out = **in
	}
	if in.ReverseProxyHTTPSPort != nil {
		in, out := &in.ReverseProxyHTTPSPort, &out.ReverseProxyHTTPSPort
		*out = new(float64)
		**out = **in
	}
	if in.Server != nil {
		in, out := &in.Server, &out.Server
		*out = new(string)
		**out = **in
	}
	if in.SetAsOidcProvider != nil {
		in, out := &in.SetAsOidcProvider, &out.SetAsOidcProvider
		*out = new(bool)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = make([]TagParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeManagerParameters.
func (in *ComputeManagerParameters) DeepCopy() *ComputeManagerParameters {
	if in == nil {
		return nil
	}
	out := new(ComputeManagerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeManagerSpec) DeepCopyInto(out *ComputeManagerSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeManagerSpec.
func (in *ComputeManagerSpec) DeepCopy() *ComputeManagerSpec {
	if in == nil {
		return nil
	}
	out := new(ComputeManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComputeManagerStatus) DeepCopyInto(out *ComputeManagerStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComputeManagerStatus.
func (in *ComputeManagerStatus) DeepCopy() *ComputeManagerStatus {
	if in == nil {
		return nil
	}
	out := new(ComputeManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialObservation) DeepCopyInto(out *CredentialObservation) {
	*out = *in
	if in.SAMLLogin != nil {
		in, out := &in.SAMLLogin, &out.SAMLLogin
		*out = make([]SAMLLoginObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SessionLogin != nil {
		in, out := &in.SessionLogin, &out.SessionLogin
		*out = make([]SessionLoginObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UsernamePasswordLogin != nil {
		in, out := &in.UsernamePasswordLogin, &out.UsernamePasswordLogin
		*out = make([]UsernamePasswordLoginObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VerifiableAsymmetricLogin != nil {
		in, out := &in.VerifiableAsymmetricLogin, &out.VerifiableAsymmetricLogin
		*out = make([]VerifiableAsymmetricLoginParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialObservation.
func (in *CredentialObservation) DeepCopy() *CredentialObservation {
	if in == nil {
		return nil
	}
	out := new(CredentialObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CredentialParameters) DeepCopyInto(out *CredentialParameters) {
	*out = *in
	if in.SAMLLogin != nil {
		in, out := &in.SAMLLogin, &out.SAMLLogin
		*out = make([]SAMLLoginParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SessionLogin != nil {
		in, out := &in.SessionLogin, &out.SessionLogin
		*out = make([]SessionLoginParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UsernamePasswordLogin != nil {
		in, out := &in.UsernamePasswordLogin, &out.UsernamePasswordLogin
		*out = make([]UsernamePasswordLoginParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VerifiableAsymmetricLogin != nil {
		in, out := &in.VerifiableAsymmetricLogin, &out.VerifiableAsymmetricLogin
		*out = make([]VerifiableAsymmetricLoginParameters, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CredentialParameters.
func (in *CredentialParameters) DeepCopy() *CredentialParameters {
	if in == nil {
		return nil
	}
	out := new(CredentialParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionCertificateObservation) DeepCopyInto(out *ExtensionCertificateObservation) {
	*out = *in
	if in.PemEncoded != nil {
		in, out := &in.PemEncoded, &out.PemEncoded
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionCertificateObservation.
func (in *ExtensionCertificateObservation) DeepCopy() *ExtensionCertificateObservation {
	if in == nil {
		return nil
	}
	out := new(ExtensionCertificateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExtensionCertificateParameters) DeepCopyInto(out *ExtensionCertificateParameters) {
	*out = *in
	if in.PemEncoded != nil {
		in, out := &in.PemEncoded, &out.PemEncoded
		*out = new(string)
		**out = **in
	}
	out.PrivateKeySecretRef = in.PrivateKeySecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExtensionCertificateParameters.
func (in *ExtensionCertificateParameters) DeepCopy() *ExtensionCertificateParameters {
	if in == nil {
		return nil
	}
	out := new(ExtensionCertificateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLLoginObservation) DeepCopyInto(out *SAMLLoginObservation) {
	*out = *in
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLLoginObservation.
func (in *SAMLLoginObservation) DeepCopy() *SAMLLoginObservation {
	if in == nil {
		return nil
	}
	out := new(SAMLLoginObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SAMLLoginParameters) DeepCopyInto(out *SAMLLoginParameters) {
	*out = *in
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SAMLLoginParameters.
func (in *SAMLLoginParameters) DeepCopy() *SAMLLoginParameters {
	if in == nil {
		return nil
	}
	out := new(SAMLLoginParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionLoginObservation) DeepCopyInto(out *SessionLoginObservation) {
	*out = *in
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionLoginObservation.
func (in *SessionLoginObservation) DeepCopy() *SessionLoginObservation {
	if in == nil {
		return nil
	}
	out := new(SessionLoginObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SessionLoginParameters) DeepCopyInto(out *SessionLoginParameters) {
	*out = *in
	out.SessionIDSecretRef = in.SessionIDSecretRef
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SessionLoginParameters.
func (in *SessionLoginParameters) DeepCopy() *SessionLoginParameters {
	if in == nil {
		return nil
	}
	out := new(SessionLoginParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagObservation) DeepCopyInto(out *TagObservation) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagObservation.
func (in *TagObservation) DeepCopy() *TagObservation {
	if in == nil {
		return nil
	}
	out := new(TagObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TagParameters) DeepCopyInto(out *TagParameters) {
	*out = *in
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(string)
		**out = **in
	}
	if in.Tag != nil {
		in, out := &in.Tag, &out.Tag
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TagParameters.
func (in *TagParameters) DeepCopy() *TagParameters {
	if in == nil {
		return nil
	}
	out := new(TagParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsernamePasswordLoginObservation) DeepCopyInto(out *UsernamePasswordLoginObservation) {
	*out = *in
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsernamePasswordLoginObservation.
func (in *UsernamePasswordLoginObservation) DeepCopy() *UsernamePasswordLoginObservation {
	if in == nil {
		return nil
	}
	out := new(UsernamePasswordLoginObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UsernamePasswordLoginParameters) DeepCopyInto(out *UsernamePasswordLoginParameters) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.Thumbprint != nil {
		in, out := &in.Thumbprint, &out.Thumbprint
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UsernamePasswordLoginParameters.
func (in *UsernamePasswordLoginParameters) DeepCopy() *UsernamePasswordLoginParameters {
	if in == nil {
		return nil
	}
	out := new(UsernamePasswordLoginParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifiableAsymmetricLoginObservation) DeepCopyInto(out *VerifiableAsymmetricLoginObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifiableAsymmetricLoginObservation.
func (in *VerifiableAsymmetricLoginObservation) DeepCopy() *VerifiableAsymmetricLoginObservation {
	if in == nil {
		return nil
	}
	out := new(VerifiableAsymmetricLoginObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VerifiableAsymmetricLoginParameters) DeepCopyInto(out *VerifiableAsymmetricLoginParameters) {
	*out = *in
	out.AsymmetricCredentialSecretRef = in.AsymmetricCredentialSecretRef
	out.CredentialKeySecretRef = in.CredentialKeySecretRef
	out.CredentialVerifierSecretRef = in.CredentialVerifierSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VerifiableAsymmetricLoginParameters.
func (in *VerifiableAsymmetricLoginParameters) DeepCopy() *VerifiableAsymmetricLoginParameters {
	if in == nil {
		return nil
	}
	out := new(VerifiableAsymmetricLoginParameters)
	in.DeepCopyInto(out)
	return out
}
