/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this PolicyEvpnConfig
func (mg *PolicyEvpnConfig) GetTerraformResourceType() string {
	return "nsxt_policy_evpn_config"
}

// GetConnectionDetailsMapping for this PolicyEvpnConfig
func (tr *PolicyEvpnConfig) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this PolicyEvpnConfig
func (tr *PolicyEvpnConfig) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this PolicyEvpnConfig
func (tr *PolicyEvpnConfig) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this PolicyEvpnConfig
func (tr *PolicyEvpnConfig) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this PolicyEvpnConfig
func (tr *PolicyEvpnConfig) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this PolicyEvpnConfig
func (tr *PolicyEvpnConfig) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this PolicyEvpnConfig using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *PolicyEvpnConfig) LateInitialize(attrs []byte) (bool, error) {
	params := &PolicyEvpnConfigParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *PolicyEvpnConfig) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this PolicyEvpnTenant
func (mg *PolicyEvpnTenant) GetTerraformResourceType() string {
	return "nsxt_policy_evpn_tenant"
}

// GetConnectionDetailsMapping for this PolicyEvpnTenant
func (tr *PolicyEvpnTenant) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this PolicyEvpnTenant
func (tr *PolicyEvpnTenant) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this PolicyEvpnTenant
func (tr *PolicyEvpnTenant) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this PolicyEvpnTenant
func (tr *PolicyEvpnTenant) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this PolicyEvpnTenant
func (tr *PolicyEvpnTenant) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this PolicyEvpnTenant
func (tr *PolicyEvpnTenant) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this PolicyEvpnTenant using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *PolicyEvpnTenant) LateInitialize(attrs []byte) (bool, error) {
	params := &PolicyEvpnTenantParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *PolicyEvpnTenant) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this PolicyEvpnTunnelEndPoint
func (mg *PolicyEvpnTunnelEndPoint) GetTerraformResourceType() string {
	return "nsxt_policy_evpn_tunnel_endpoint"
}

// GetConnectionDetailsMapping for this PolicyEvpnTunnelEndPoint
func (tr *PolicyEvpnTunnelEndPoint) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this PolicyEvpnTunnelEndPoint
func (tr *PolicyEvpnTunnelEndPoint) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this PolicyEvpnTunnelEndPoint
func (tr *PolicyEvpnTunnelEndPoint) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this PolicyEvpnTunnelEndPoint
func (tr *PolicyEvpnTunnelEndPoint) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this PolicyEvpnTunnelEndPoint
func (tr *PolicyEvpnTunnelEndPoint) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this PolicyEvpnTunnelEndPoint
func (tr *PolicyEvpnTunnelEndPoint) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this PolicyEvpnTunnelEndPoint using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *PolicyEvpnTunnelEndPoint) LateInitialize(attrs []byte) (bool, error) {
	params := &PolicyEvpnTunnelEndPointParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *PolicyEvpnTunnelEndPoint) GetTerraformSchemaVersion() int {
	return 0
}

// GetTerraformResourceType returns Terraform resource type for this PolicyVniPool
func (mg *PolicyVniPool) GetTerraformResourceType() string {
	return "nsxt_policy_vni_pool"
}

// GetConnectionDetailsMapping for this PolicyVniPool
func (tr *PolicyVniPool) GetConnectionDetailsMapping() map[string]string {
	return nil
}

// GetObservation of this PolicyVniPool
func (tr *PolicyVniPool) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this PolicyVniPool
func (tr *PolicyVniPool) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this PolicyVniPool
func (tr *PolicyVniPool) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this PolicyVniPool
func (tr *PolicyVniPool) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this PolicyVniPool
func (tr *PolicyVniPool) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this PolicyVniPool using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *PolicyVniPool) LateInitialize(attrs []byte) (bool, error) {
	params := &PolicyVniPoolParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *PolicyVniPool) GetTerraformSchemaVersion() int {
	return 0
}
