/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	"github.com/pkg/errors"

	"github.com/upbound/upjet/pkg/resource"
	"github.com/upbound/upjet/pkg/resource/json"
)

// GetTerraformResourceType returns Terraform resource type for this TransportNode
func (mg *TransportNode) GetTerraformResourceType() string {
	return "nsxt_transport_node"
}

// GetConnectionDetailsMapping for this TransportNode
func (tr *TransportNode) GetConnectionDetailsMapping() map[string]string {
	return map[string]string{"edge_node[*].deployment_config[*].node_user_settings[*].audit_password": "spec.forProvider.edgeNode[*].deploymentConfig[*].nodeUserSettings[*].auditPasswordSecretRef", "edge_node[*].deployment_config[*].node_user_settings[*].cli_password": "spec.forProvider.edgeNode[*].deploymentConfig[*].nodeUserSettings[*].cliPasswordSecretRef", "edge_node[*].deployment_config[*].node_user_settings[*].root_password": "spec.forProvider.edgeNode[*].deploymentConfig[*].nodeUserSettings[*].rootPasswordSecretRef", "host_node[*].host_credential[*].password": "spec.forProvider.hostNode[*].hostCredential[*].passwordSecretRef", "public_cloud_gateway_node[*].deployment_config[*].node_user_settings[*].audit_password": "spec.forProvider.publicCloudGatewayNode[*].deploymentConfig[*].nodeUserSettings[*].auditPasswordSecretRef", "public_cloud_gateway_node[*].deployment_config[*].node_user_settings[*].cli_password": "spec.forProvider.publicCloudGatewayNode[*].deploymentConfig[*].nodeUserSettings[*].cliPasswordSecretRef", "public_cloud_gateway_node[*].deployment_config[*].node_user_settings[*].root_password": "spec.forProvider.publicCloudGatewayNode[*].deploymentConfig[*].nodeUserSettings[*].rootPasswordSecretRef"}
}

// GetObservation of this TransportNode
func (tr *TransportNode) GetObservation() (map[string]any, error) {
	o, err := json.TFParser.Marshal(tr.Status.AtProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(o, &base)
}

// SetObservation for this TransportNode
func (tr *TransportNode) SetObservation(obs map[string]any) error {
	p, err := json.TFParser.Marshal(obs)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Status.AtProvider)
}

// GetID returns ID of underlying Terraform resource of this TransportNode
func (tr *TransportNode) GetID() string {
	if tr.Status.AtProvider.ID == nil {
		return ""
	}
	return *tr.Status.AtProvider.ID
}

// GetParameters of this TransportNode
func (tr *TransportNode) GetParameters() (map[string]any, error) {
	p, err := json.TFParser.Marshal(tr.Spec.ForProvider)
	if err != nil {
		return nil, err
	}
	base := map[string]any{}
	return base, json.TFParser.Unmarshal(p, &base)
}

// SetParameters for this TransportNode
func (tr *TransportNode) SetParameters(params map[string]any) error {
	p, err := json.TFParser.Marshal(params)
	if err != nil {
		return err
	}
	return json.TFParser.Unmarshal(p, &tr.Spec.ForProvider)
}

// LateInitialize this TransportNode using its observed tfState.
// returns True if there are any spec changes for the resource.
func (tr *TransportNode) LateInitialize(attrs []byte) (bool, error) {
	params := &TransportNodeParameters{}
	if err := json.TFParser.Unmarshal(attrs, params); err != nil {
		return false, errors.Wrap(err, "failed to unmarshal Terraform state parameters for late-initialization")
	}
	opts := []resource.GenericLateInitializerOption{resource.WithZeroValueJSONOmitEmptyFilter(resource.CNameWildcard)}

	li := resource.NewGenericLateInitializer(opts...)
	return li.LateInitialize(&tr.Spec.ForProvider, params)
}

// GetTerraformSchemaVersion returns the associated Terraform schema version
func (tr *TransportNode) GetTerraformSchemaVersion() int {
	return 0
}
