/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type FailureDomainObservation struct {

	// Description for this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Set preference for failure domain
	PreferredEdgeServices *string `json:"preferredEdgeServices,omitempty" tf:"preferred_edge_services,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []TagObservation `json:"tag,omitempty" tf:"tag,omitempty"`
}

type FailureDomainParameters struct {

	// Description for this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// Display name for this resource
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Set preference for failure domain
	// +kubebuilder:validation:Optional
	PreferredEdgeServices *string `json:"preferredEdgeServices,omitempty" tf:"preferred_edge_services,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []TagParameters `json:"tag,omitempty" tf:"tag,omitempty"`
}

type TagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type TagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// FailureDomainSpec defines the desired state of FailureDomain
type FailureDomainSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FailureDomainParameters `json:"forProvider"`
}

// FailureDomainStatus defines the observed state of FailureDomain.
type FailureDomainStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FailureDomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// FailureDomain is the Schema for the FailureDomains API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type FailureDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="self.managementPolicy == 'ObserveOnly' || has(self.forProvider.displayName)",message="displayName is a required parameter"
	Spec   FailureDomainSpec   `json:"spec"`
	Status FailureDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FailureDomainList contains a list of FailureDomains
type FailureDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []FailureDomain `json:"items"`
}

// Repository type metadata.
var (
	FailureDomain_Kind             = "FailureDomain"
	FailureDomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: FailureDomain_Kind}.String()
	FailureDomain_KindAPIVersion   = FailureDomain_Kind + "." + CRDGroupVersion.String()
	FailureDomain_GroupVersionKind = CRDGroupVersion.WithKind(FailureDomain_Kind)
)

func init() {
	SchemeBuilder.Register(&FailureDomain{}, &FailureDomainList{})
}
