/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LbHttpsMonitorObservation struct {

	// Verification depth in the server certificate chain
	CertificateChainDepth *float64 `json:"certificateChainDepth,omitempty" tf:"certificate_chain_depth,omitempty"`

	// Supported SSL cipher list
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// client certificate can be specified to support client authentication
	ClientCertificateID *string `json:"clientCertificateId,omitempty" tf:"client_certificate_id,omitempty"`

	// Description of this resource
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of this resource. Defaults to ID if not set
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Number of consecutive checks that must fail before marking it down
	FallCount *float64 `json:"fallCount,omitempty" tf:"fall_count,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The frequency at which the system issues the monitor check (in seconds)
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// This flag is set to true when all the ciphers and protocols are secure. It is set to false when one of the ciphers or protocols is insecure
	IsSecure *bool `json:"isSecure,omitempty" tf:"is_secure,omitempty"`

	// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not supported
	MonitorPort *string `json:"monitorPort,omitempty" tf:"monitor_port,omitempty"`

	// SSL versions TLS1.1 and TLS1.2 are supported and enabled by default. SSLv2, SSLv3, and TLS1.0 are supported, but disabled by default
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`

	// String to send as HTTP health check request body. Valid only for certain HTTP methods like POST
	RequestBody *string `json:"requestBody,omitempty" tf:"request_body,omitempty"`

	// Array of HTTP request headers
	RequestHeader []RequestHeaderObservation `json:"requestHeader,omitempty" tf:"request_header,omitempty"`

	// Health check method for HTTP monitor type
	RequestMethod *string `json:"requestMethod,omitempty" tf:"request_method,omitempty"`

	// URL used for HTTP monitor
	RequestURL *string `json:"requestUrl,omitempty" tf:"request_url,omitempty"`

	// HTTP request version
	RequestVersion *string `json:"requestVersion,omitempty" tf:"request_version,omitempty"`

	// If HTTP specified, healthcheck HTTP response body is matched against the specified string (regular expressions not supported), and succeeds only if there is a match
	ResponseBody *string `json:"responseBody,omitempty" tf:"response_body,omitempty"`

	// The HTTP response status code should be a valid HTTP status code
	ResponseStatusCodes []*float64 `json:"responseStatusCodes,omitempty" tf:"response_status_codes,omitempty"`

	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected
	Revision *float64 `json:"revision,omitempty" tf:"revision,omitempty"`

	// Number of consecutive checks that must pass before marking it up
	RiseCount *float64 `json:"riseCount,omitempty" tf:"rise_count,omitempty"`

	// Server authentication mode
	ServerAuth *string `json:"serverAuth,omitempty" tf:"server_auth,omitempty"`

	// If server auth type is REQUIRED, server certificate must be signed by one of the CAs
	ServerAuthCAIds []*string `json:"serverAuthCaIds,omitempty" tf:"server_auth_ca_ids,omitempty"`

	// Certificate Revocation List (CRL) to disallow compromised server certificates
	ServerAuthCrlIds []*string `json:"serverAuthCrlIds,omitempty" tf:"server_auth_crl_ids,omitempty"`

	// Set of opaque identifiers meaningful to the user
	Tag []TagObservation `json:"tag,omitempty" tf:"tag,omitempty"`

	// Number of seconds the target has to respond to the monitor request
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type LbHttpsMonitorParameters struct {

	// Verification depth in the server certificate chain
	// +kubebuilder:validation:Optional
	CertificateChainDepth *float64 `json:"certificateChainDepth,omitempty" tf:"certificate_chain_depth,omitempty"`

	// Supported SSL cipher list
	// +kubebuilder:validation:Optional
	Ciphers []*string `json:"ciphers,omitempty" tf:"ciphers,omitempty"`

	// client certificate can be specified to support client authentication
	// +kubebuilder:validation:Optional
	ClientCertificateID *string `json:"clientCertificateId,omitempty" tf:"client_certificate_id,omitempty"`

	// Description of this resource
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The display name of this resource. Defaults to ID if not set
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Number of consecutive checks that must fail before marking it down
	// +kubebuilder:validation:Optional
	FallCount *float64 `json:"fallCount,omitempty" tf:"fall_count,omitempty"`

	// The frequency at which the system issues the monitor check (in seconds)
	// +kubebuilder:validation:Optional
	Interval *float64 `json:"interval,omitempty" tf:"interval,omitempty"`

	// If the monitor port is specified, it would override pool member port setting for healthcheck. A port range is not supported
	// +kubebuilder:validation:Optional
	MonitorPort *string `json:"monitorPort,omitempty" tf:"monitor_port,omitempty"`

	// SSL versions TLS1.1 and TLS1.2 are supported and enabled by default. SSLv2, SSLv3, and TLS1.0 are supported, but disabled by default
	// +kubebuilder:validation:Optional
	Protocols []*string `json:"protocols,omitempty" tf:"protocols,omitempty"`

	// String to send as HTTP health check request body. Valid only for certain HTTP methods like POST
	// +kubebuilder:validation:Optional
	RequestBody *string `json:"requestBody,omitempty" tf:"request_body,omitempty"`

	// Array of HTTP request headers
	// +kubebuilder:validation:Optional
	RequestHeader []RequestHeaderParameters `json:"requestHeader,omitempty" tf:"request_header,omitempty"`

	// Health check method for HTTP monitor type
	// +kubebuilder:validation:Optional
	RequestMethod *string `json:"requestMethod,omitempty" tf:"request_method,omitempty"`

	// URL used for HTTP monitor
	// +kubebuilder:validation:Optional
	RequestURL *string `json:"requestUrl,omitempty" tf:"request_url,omitempty"`

	// HTTP request version
	// +kubebuilder:validation:Optional
	RequestVersion *string `json:"requestVersion,omitempty" tf:"request_version,omitempty"`

	// If HTTP specified, healthcheck HTTP response body is matched against the specified string (regular expressions not supported), and succeeds only if there is a match
	// +kubebuilder:validation:Optional
	ResponseBody *string `json:"responseBody,omitempty" tf:"response_body,omitempty"`

	// The HTTP response status code should be a valid HTTP status code
	// +kubebuilder:validation:Optional
	ResponseStatusCodes []*float64 `json:"responseStatusCodes,omitempty" tf:"response_status_codes,omitempty"`

	// Number of consecutive checks that must pass before marking it up
	// +kubebuilder:validation:Optional
	RiseCount *float64 `json:"riseCount,omitempty" tf:"rise_count,omitempty"`

	// Server authentication mode
	// +kubebuilder:validation:Optional
	ServerAuth *string `json:"serverAuth,omitempty" tf:"server_auth,omitempty"`

	// If server auth type is REQUIRED, server certificate must be signed by one of the CAs
	// +kubebuilder:validation:Optional
	ServerAuthCAIds []*string `json:"serverAuthCaIds,omitempty" tf:"server_auth_ca_ids,omitempty"`

	// Certificate Revocation List (CRL) to disallow compromised server certificates
	// +kubebuilder:validation:Optional
	ServerAuthCrlIds []*string `json:"serverAuthCrlIds,omitempty" tf:"server_auth_crl_ids,omitempty"`

	// Set of opaque identifiers meaningful to the user
	// +kubebuilder:validation:Optional
	Tag []TagParameters `json:"tag,omitempty" tf:"tag,omitempty"`

	// Number of seconds the target has to respond to the monitor request
	// +kubebuilder:validation:Optional
	Timeout *float64 `json:"timeout,omitempty" tf:"timeout,omitempty"`
}

type RequestHeaderObservation struct {

	// Header name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Header value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type RequestHeaderParameters struct {

	// Header name
	// +kubebuilder:validation:Required
	Name *string `json:"name" tf:"name,omitempty"`

	// Header value
	// +kubebuilder:validation:Required
	Value *string `json:"value" tf:"value,omitempty"`
}

type TagObservation struct {
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

type TagParameters struct {

	// +kubebuilder:validation:Optional
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`

	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`
}

// LbHttpsMonitorSpec defines the desired state of LbHttpsMonitor
type LbHttpsMonitorSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LbHttpsMonitorParameters `json:"forProvider"`
}

// LbHttpsMonitorStatus defines the observed state of LbHttpsMonitor.
type LbHttpsMonitorStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LbHttpsMonitorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// LbHttpsMonitor is the Schema for the LbHttpsMonitors API. <no value>
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,nsxt}
type LbHttpsMonitor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LbHttpsMonitorSpec   `json:"spec"`
	Status            LbHttpsMonitorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LbHttpsMonitorList contains a list of LbHttpsMonitors
type LbHttpsMonitorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LbHttpsMonitor `json:"items"`
}

// Repository type metadata.
var (
	LbHttpsMonitor_Kind             = "LbHttpsMonitor"
	LbHttpsMonitor_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LbHttpsMonitor_Kind}.String()
	LbHttpsMonitor_KindAPIVersion   = LbHttpsMonitor_Kind + "." + CRDGroupVersion.String()
	LbHttpsMonitor_GroupVersionKind = CRDGroupVersion.WithKind(LbHttpsMonitor_Kind)
)

func init() {
	SchemeBuilder.Register(&LbHttpsMonitor{}, &LbHttpsMonitorList{})
}
